In [4]:
import pandas as pd 
# Create dataframe
data = {
    'Company': ['GOOG', 'GOOG', 'mist', 'mist', 'fb', 'fb'],
    'personL': ['sam', 'charlie', 'amy', 'vanessa', 'carl', 'sarah'],
    'sales': [200, 120, 340, 124, 243, 350]}

In [5]:
data

{'Company': ['GOOG', 'GOOG', 'mist', 'mist', 'fb', 'fb'],
 'personL': ['sam', 'charlie', 'amy', 'vanessa', 'carl', 'sarah'],
 'sales': [200, 120, 340, 124, 243, 350]}

In [6]:
# Create DataFrame
df = pd.DataFrame(data)

In [7]:
df

  Company  personL  sales
0    GOOG      sam    200
1    GOOG  charlie    120
2    mist      amy    340
3    mist  vanessa    124
4      fb     carl    243
5      fb    sarah    350

In [8]:
by_comp = df.groupby('Company')

In [9]:
by_comp

In [10]:
df.groupby('Company')['sales'].mean()

Company
GOOG    160.0
fb      296.5
mist    232.0
Name: sales, dtype: float64

In [11]:
df.groupby('Company')['sales'].max()

Company
GOOG    200
fb      350
mist    340
Name: sales, dtype: int64

In [12]:
by_comp.describe()

        sales
        count   mean         std    min     25%    50%     75%    max
Company
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
fb        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
mist      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [13]:
by_comp.describe().transpose()

Company            GOOG          fb        mist
sales count    2.000000    2.000000    2.000000
      mean   160.000000  296.500000  232.000000
      std     56.568542   75.660426  152.735065
      min    120.000000  243.000000  124.000000
      25%    140.000000  269.750000  178.000000
      50%    160.000000  296.500000  232.000000
      75%    180.000000  323.250000  286.000000
      max    200.000000  350.000000  340.000000

In [14]:
by_comp.describe().transpose()['GOOG']

sales  count      2.000000
       mean     160.000000
       std       56.568542
       min      120.000000
       25%      140.000000
       50%      160.000000
       75%      180.000000
       max      200.000000
Name: GOOG, dtype: float64